#!/usr/bin/env node
/**
 * library-audit.mjs — dead-asset + catalog integrity gate for the shared 3D model library.
 *
 * Reads `buddy-kit/client/city-common/library.js` and cross-checks it against the files
 * actually on disk under `buddy-kit/client/library/`. Emits:
 *   1. MISSING   — a LIBRARY entry points at a glb that does not exist on disk (FATAL).
 *   2. NO_THUMB  — a catalogued entry has no `library/thumbnails/<id>.png` (FATAL — the
 *                  picker renders a broken card).
 *   3. DUPLICATE — two entries point at the same glb file (WARNING — usually means a
 *                  cataloguing mistake, but is not a runtime break).
 *   4. ORPHANS   — glbs on disk with no LIBRARY entry (WARNING — deliberately kept for
 *                  future cataloguing, but should never grow silently without a review).
 *
 * Exit code: 0 = clean (orphans allowed), 1 = any MISSING/NO_THUMB/DUPLICATE failure.
 * Run from P5 Programme/. Optional `--orphan-limit N` makes orphan overage fail too.
 *
 * Usage:
 *   node scripts/library-audit.mjs                      # check only
 *   node scripts/library-audit.mjs --orphan-limit 5     # fail if >5 orphans
 *   node scripts/library-audit.mjs --write-report       # rewrite library/ORPHANED-GLBS.md
 */
import { readdirSync, existsSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LIBRARY } from '../buddy-kit/client/city-common/library.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const CLIENT = join(ROOT, 'buddy-kit/client');
const LIB_DIR = join(CLIENT, 'library');
const THUMBS_DIR = join(LIB_DIR, 'thumbnails');
const REPORT_PATH = join(LIB_DIR, 'ORPHANED-GLBS.md');

const args = process.argv.slice(2);
const orphanLimit = (() => {
  const i = args.indexOf('--orphan-limit');
  return i >= 0 ? Number(args[i + 1]) : Infinity;
})();
const writeReport = args.includes('--write-report');

/** Walk a dir, returning relative paths (forward-slash) matching a suffix filter. */
function walk(dir, suffix) {
  const out = [];
  const rec = (d, prefix = '') => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const rel = prefix ? `${prefix}/${e.name}` : e.name;
      if (e.isDirectory()) rec(join(d, e.name), rel);
      else if (suffix && rel.endsWith(suffix)) out.push(rel);
    }
  };
  rec(dir);
  return out;
}

/** Resolve a LIBRARY glb path (relative to city-common/) to an absolute file path. */
function resolveGlb(glb) {
  const cleaned = String(glb).replace(/^\.\.\//, '');
  return join(CLIENT, cleaned);
}

// ── 1. Catalog-derived facts ──────────────────────────────────────────────────
const missing = [];
const noThumb = [];
const dupCount = new Map();
const refPaths = new Set();
const oversized = [];   // GLBs that risk breaking the Workers deploy (>24MiB) or hammer tablets (>15MiB)
const OVERFAIL_BYTES = 24 * 1024 * 1024;   // Cloudflare Workers assets reject >25MiB — fail before deploy
const OVERWARN_BYTES = 15 * 1024 * 1024;   // heavy tablet downloads — warn

for (const e of LIBRARY) {
  const abs = resolveGlb(e.glb);
  if (!existsSync(abs)) missing.push({ id: e.id, glb: e.glb });
  refPaths.add(e.glb);
  if (!existsSync(join(THUMBS_DIR, `${e.id}.png`))) noThumb.push(e.id);
  const key = e.glb.replace(/^\.\.\//, '');
  dupCount.set(key, (dupCount.get(key) || 0) + 1);
  if (existsSync(abs)) {
    const bytes = statSync(abs).size;
    if (bytes > OVERFAIL_BYTES) oversized.push({ id: e.id, glb: e.glb, bytes, fatal: true });
    else if (bytes > OVERWARN_BYTES) oversized.push({ id: e.id, glb: e.glb, bytes, fatal: false });
  }
}
const duplicates = [...dupCount.entries()].filter(([, n]) => n > 1);
const oversizedFatal = oversized.filter((o) => o.fatal);

// ── 2. Disk-derived facts ────────────────────────────────────────────────────
const diskGlbs = new Set(walk(LIB_DIR, '.glb'));
const referencedOnDisk = new Set(
  [...refPaths].map((g) => g.replace(/^\.\.\//, '').replace(/^library\//, ''))
);
const orphans = [...diskGlbs].filter((p) => !referencedOnDisk.has(p)).sort();

// ── 3. Report ────────────────────────────────────────────────────────────────
const lines = [];
lines.push('# Orphaned GLB Identification Report');
lines.push('');
lines.push(`Auto-generated by \`scripts/library-audit.mjs\` on ${new Date().toISOString().slice(0, 10)}.`);
lines.push('');
lines.push(`- **Catalogued entries:** ${LIBRARY.length}`);
lines.push(`- **GLBs on disk:** ${diskGlbs.size}`);
lines.push(`- **Referenced by library.js:** ${refPaths.size}`);
lines.push(`- **Orphaned (no entry):** ${orphans.length}`);
lines.push(`- **Missing on disk (referenced but absent):** ${missing.length}`);
lines.push(`- **Entries with no thumbnail:** ${noThumb.length}`);
lines.push(`- **Duplicate glb paths:** ${duplicates.length}`);
lines.push('');
lines.push('> Orphans are DELIBERATELY kept in the library so they can be catalogued later.');
lines.push('> This report fails CI when the count grows past the orphan limit set in CI.');
lines.push('');
lines.push('## Orphans');
lines.push('');
if (orphans.length) {
  for (const o of orphans) lines.push(`- \`${o}\``);
} else {
  lines.push('_None._');
}

const reportText = lines.join('\n') + '\n';
if (writeReport) writeFileSync(REPORT_PATH, reportText);

// ── 4. Verdict ───────────────────────────────────────────────────────────────
const fatal = missing.length + noThumb.length + duplicates.length + oversizedFatal.length;
const orphanFail = orphans.length > orphanLimit;
const status = fatal === 0 && !orphanFail ? 'PASS' : 'FAIL';

console.log(`[library-audit] entries=${LIBRARY.length} onDisk=${diskGlbs.size} orphans=${orphans.length} missing=${missing.length} noThumb=${noThumb.length} dup=${duplicates.length} oversized=${oversized.length}(fatal=${oversizedFatal.length})`);
if (missing.length) {
  console.log(`[library-audit] MISSING (fatal):`);
  for (const m of missing) console.log(`  ✗ ${m.id} -> ${m.glb}`);
}
if (noThumb.length) {
  console.log(`[library-audit] NO_THUMB (fatal):`);
  for (const id of noThumb.slice(0, 20)) console.log(`  ✗ ${id}`);
}
if (duplicates.length) {
  console.log(`[library-audit] DUPLICATE (warning):`);
  for (const [p, n] of duplicates) console.log(`  ⚠ ${p} ×${n}`);
}
if (oversized.length) {
  console.log(`[library-audit] OVERSIZED GLB (${oversizedFatal.length ? 'fatal — >24MiB breaks the Workers deploy' : 'warnings — heavy tablet downloads'}):`);
  for (const o of oversized) console.log(`  ${o.fatal ? '✗' : '⚠'} ${o.id} ${o.glb} ${(o.bytes / 1048576).toFixed(1)}MiB`);
}
if (orphans.length) {
  console.log(`[library-audit] ORPHANS (warning):`);
  for (const o of orphans) console.log(`  ⚠ ${o}`);
  if (orphanFail) console.log(`[library-audit] ORPHAN LIMIT EXCEEDED (limit ${orphanLimit})`);
}
console.log(`[library-audit] ${status}`);
process.exit(fatal === 0 && !orphanFail ? 0 : 1);
