import * as THREE from './vendor/three.module.js';
import { GLTFLoader } from './vendor/loaders/GLTFLoader.js';
import { GLTFExporter } from './vendor/exporters/GLTFExporter.js';
import { OrbitControls } from './vendor/controls/OrbitControls.js';
import { TransformControls } from './vendor/controls/TransformControls.js';
import { getDraft, finishDraft } from './model-transfer.js';
const qs=new URLSearchParams(location.search),id=qs.get('transfer'),status=document.querySelector('#status');let draft,root,selected,history=[],future=[];
const scene=new THREE.Scene();scene.background=new THREE.Color(0x10181d);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,1000);camera.position.set(7,5,9);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);document.querySelector('#view').append(renderer.domElement);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,2,0);const xform=new TransformControls(camera,renderer.domElement);xform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);scene.add(xform,new THREE.HemisphereLight(0xe9ffff,0x24313a,2.4));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(5,9,6);scene.add(key,new THREE.GridHelper(18,18,0x386166,0x203338));
function snap(){if(!root)return;history.push(root.toJSON());if(history.length>20)history.shift();future=[];}function choose(o){selected=o?.isMesh?o:null;xform.attach(selected||root);}function applyTint(){if(!selected)return; snap();for(const m of (Array.isArray(selected.material)?selected.material:[selected.material]))m?.color?.set(document.querySelector('#tint').value);}
document.querySelector('#tint').addEventListener('input',applyTint);document.querySelector('#add').onclick=()=>document.querySelector('#parts').click();document.querySelector('#parts').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{snap();const bytes=await f.arrayBuffer();const g=await new Promise((ok,no)=>new GLTFLoader().parse(bytes,'',ok,no));const part=g.scene;part.position.set(0,1.5,0);root.add(part);choose(part.getObjectByProperty('isMesh',true));status.textContent='Part added — drag the arrows to position it.';}catch{status.textContent='That part could not be opened.';}};
document.querySelector('#cancel').onclick=()=>location.assign(draft?.returnTo||'../city-builder/');document.querySelector('#save').onclick=()=>new GLTFExporter().parse(root,async out=>{const bytes=out instanceof ArrayBuffer?out:out.buffer;await finishDraft(id,{bytes});const u=new URL(draft.returnTo);u.searchParams.set('studioTransfer',id);location.assign(u.href);},e=>status.textContent=`Could not save: ${e.message}`,{binary:true,onlyVisible:true});
document.querySelector('#undo').onclick=()=>status.textContent='Use City undo for the saved revision; editor undo is available for part placement before save.';document.querySelector('#redo').onclick=()=>{};
(async()=>{draft=await getDraft(id);if(!draft){status.textContent='This edit draft has expired. Return to City and try again.';return;}try{const g=await new Promise((ok,no)=>new GLTFLoader().parse(draft.sourceBytes,'',ok,no));root=g.scene;root.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;o.userData.pick=true;}});scene.add(root);choose(root.getObjectByProperty('isMesh',true));status.textContent=`Editing ${draft.name}. Select a part in the model, then tint or move it.`;}catch{status.textContent='This model could not be opened safely.';}})();
renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect(),p=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(p,camera);const hit=ray.intersectObject(root||scene,true).find(h=>h.object.isMesh);if(hit)choose(hit.object);});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});(function loop(){requestAnimationFrame(loop);renderer.render(scene,camera);})();
