import { test, expect } from '@playwright/test';

test('recycling station runs examples and personal photos without a sorter', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('p5_city_planner_layout_v1', JSON.stringify({version:2,scaleMeters:2000,roads:[],buildings:[],parks:[]})));
  await page.goto('/city-builder/?activity=recycling&exercise=batch-1');
  if(await page.locator('#entry-local').isVisible())await page.locator('#entry-local').click();
  const panel=page.locator('.city-activity-panel');
  await expect(panel).toHaveAttribute('data-state','ready',{timeout:90000});
  await expect(panel.locator('[data-status]')).toHaveText('No model connected — all items need human check');
  await expect(panel.locator('[data-act="run"]')).toBeEnabled();
  await expect(panel.locator('[data-act="step"]')).toBeEnabled();
  const before=await page.evaluate(async()=>{
    const {createProjectStore}=await import('/city-common/project-store.js');
    const store=createProjectStore();await store.openActiveProject();
    const saved={scenario:'batch-1',outcome:'completed',capabilityId:'saved-model',results:[],score:{humanChecked:0}};
    await store.mutate(p=>{p.projects.cityActivities||={};p.projects.cityActivities.recycling=saved;return p;},{reason:'test-saved-result'});
    const economy=await store.readEconomy();store.close();return economy;
  });
  const first=await page.evaluate(()=>window.__cityActivities.trial.rows[0].id);
  await panel.locator('[data-act="step"]').click();
  const firstPosition=await page.evaluate(id=>{const a=window.__cityActivities;a.update(0);return window.__scene.getObjectByName(id)?.position.toArray();},first);
  await page.evaluate(()=>{const a=window.__cityActivities;for(let i=0;i<13;i++)a.trial.step();a.update(0);});
  const movedPosition=await page.evaluate(id=>window.__scene.getObjectByName(id)?.position.toArray(),first);
  expect(firstPosition).toBeTruthy();expect(movedPosition).toBeTruthy();expect(movedPosition[0]).not.toBe(firstPosition[0]);
  await expect(panel.locator('[data-evidence]')).toContainText('Human review — no model connected');
  await panel.locator('[data-act="run"]').click();
  await page.evaluate(()=>{const a=window.__cityActivities;for(let i=0;i<600&&a.trial.state==='running';i++)a.update(.1);});
  await expect(panel).toHaveAttribute('data-state','finished');
  await expect(panel.locator('[data-bin-readouts]')).toContainText('9 · 100%');
  await expect(panel.locator('[data-result]')).toContainText('9 items sent to human check');
  expect(await page.evaluate(()=>window.__cityActivities.trial.results.every(r=>r.bin==='human-check'&&r.routedBy==='human-review'))).toBe(true);
  const after=await page.evaluate(async()=>{const {createProjectStore}=await import('/city-common/project-store.js');const store=createProjectStore();await store.openActiveProject();const economy=await store.readEconomy();const saved=(await store.readSection('cityActivities')).recycling;store.close();return {economy,saved};});
  expect(after.economy).toEqual(before);
  expect(after.saved.capabilityId).toBe('saved-model');
  await panel.locator('[data-act="reset"]').click();
  await expect(panel).toHaveAttribute('data-state','ready');
  await expect(panel.locator('[data-bin-readouts]')).toContainText('0 · 0%');
  await panel.locator('[data-act="scenario"]').selectOption('personal');
  await expect(panel.locator('[data-act="run"]')).toBeDisabled();
  await expect(panel.locator('[data-act="step"]')).toBeDisabled();
  await page.evaluate(async()=>{
    const {createProjectStore}=await import('/city-common/project-store.js');
    const {writeSorterSession}=await import('/city-common/sorter-session.js');
    const store=createProjectStore(),project=await store.openActiveProject();
    const vector=Array(1024).fill(0);vector[0]=1;
    writeSorterSession({projectId:project.id,preprocessing:'mobilenet-v3-small-224-squash-f32-unit-v1',batch:[{id:'my-photo',vector}],teaching:[],selection:null});store.close();
  });
  await panel.locator('[data-act="reset"]').click();
  await expect(panel.locator('[data-waiting]')).toContainText('1 photo waiting');
  await expect(panel.locator('[data-act="run"]')).toBeEnabled();
  await panel.locator('[data-act="step"]').click();
  await panel.locator('[data-act="run"]').click();
  await page.evaluate(()=>{const a=window.__cityActivities;for(let i=0;i<60&&a.trial.state==='running';i++)a.update(.1);});
  await expect(panel).toHaveAttribute('data-state','finished');
  await expect(panel.locator('[data-result]')).toContainText('1 item sent to human check');
  expect(await page.evaluate(()=>window.__cityActivities.trial.results[0].bin)).toBe('human-check');
  await panel.locator('[data-act="reset"]').click();
  await expect(panel.locator('[data-waiting]')).toContainText('1 photo waiting · 0 sorted');
  await page.evaluate(()=>localStorage.setItem('hk_ai_city_lang_v1','zh-Hant'));
  await page.reload();
  if(await page.locator('#entry-local').isVisible())await page.locator('#entry-local').click();
  await expect(panel).toHaveAttribute('data-state','ready',{timeout:90000});
  await expect(panel.locator('[data-status]')).toHaveText('沒有連接模型——所有物品都需要人手檢查');
});
