/**
 * The buddy's durable memory: three curated markdown files we own (Setting/User/Champion).
 * Read them and compose the context block the server injects as the system prompt
 * (`turn.js`'s `composeTurnContext`, rebuilt every turn from that request's own memory), so the model
 * holds them for the turn but the child can't forge them. Curated markdown, never transcripts — teacher-visible + immune to
 * whatever the model engine's own conversation state does or doesn't retain.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** This module's own directory via import.meta.url — or null on a runtime where bundled modules
 * have no real file URL. GUARDED because module-scope evaluation is part of the bundle: the
 * Cloudflare Worker shell (web/coding agent/worker/) bundles this file for its pure per-turn
 * helpers and never calls readMemory (its seed is worker/mem-seed.mjs), and an unguarded
 * `new URL('.', import.meta.url)` crashed workerd at startup with "Invalid URL string"
 * (2026-08-11) — the whole Worker dead before the first request, for a path it would never read. */
function moduleDir() {
  try { return fileURLToPath(new URL('.', import.meta.url)); } catch { return null; }
}
const HERE = moduleDir();
// `BUDDY_MEMORY_DIR` is a TEST-ONLY seam (stateless-buddy Task 8): the gateway itself never writes
// here (see the plan — durable memory lives in the client's champion file, not server disk), so
// there is no production deploy reason to redirect this path. It exists purely so a deterministic
// test can boot the real gateway against a disposable temp dir instead of the committed
// `server/memory/` seed files, then assert that dir is byte-for-byte untouched after a full
// `/api/turn` round trip — see tests/stateless-loop.test.js. Read ONCE at module load (same as
// before), so it must be set BEFORE this module (or gateway.js, which imports it) is first
// imported — tests/helpers/start-gateway.js already follows this pattern for BUDDY_PORT/
// BUDDY_MODEL_KEY. `null` only on the no-file-URL runtime above, where nothing ever reads it.
export const MEMORY_DIR = process.env.BUDDY_MEMORY_DIR || (HERE === null ? null : join(HERE, 'memory'));

/** @returns {{setting:string,user:string,champion:string}} */
export function readMemory(dir = MEMORY_DIR) {
  // A null dir (no filesystem identity — see moduleDir) serves the same fallbacks a missing file
  // does: total, never a throw, and byte-identical to what worker/mem-seed.mjs regenerates from.
  const readOr = (f, fallback) => {
    if (dir === null) return fallback;
    try { return readFileSync(join(dir, f), 'utf8'); } catch { return fallback; }
  };
  return {
    setting: readOr('Setting.md', '# Buddy Setting\nA warm coach for a 10-year-old.'),
    user: readOr('User.md', '# About the Learner\n(No notes yet.)'),
    champion: readOr('Champion.md', '# Champion Profile\n(No abilities yet.)'),
  };
}

/**
 * The durable context injected once per lesson (as a noReply message). Not shown to the child.
 * `opsBlock` is OPTIONAL (generated by `ops-instruction.js`'s `opsInstruction(enabledOps)` — see
 * that module for why the op-proposal instruction moved out of Setting.md and into config-driven
 * generation). When omitted, the output is BYTE-IDENTICAL to before `opsBlock` existed — every
 * existing caller that doesn't pass it keeps working unchanged.
 */
export function composeInjection({ setting, user, champion, buddyName, opsBlock }) {
  return [
    setting.replace(/\(set on first run\)\.?/i, buddyName ? `${buddyName}.` : '(unnamed).'),
    ...(opsBlock ? [opsBlock] : []),
    `The child named you "${buddyName || 'Buddy'}".`,
    '--- what you remember about the learner (do not reveal these labels) ---',
    user,
    '--- the champion you are helping raise ---',
    champion,
  ].join('\n\n');
}

/**
 * Resolve the memory for one turn: prefer the client-carried payload (the stateless-buddy Task 1
 * source of truth — see AGENTS.md/the plan), fall back to the baked seed (read once at boot via
 * `readMemory()`), and re-screen each field so a hand-edited/forged champion file can't smuggle
 * unsafe text into the system prompt just because it rode in on the request body instead of disk.
 * A field is used from the payload only if it is a non-empty string AND passes `screen`; otherwise
 * that field (independently — the two fields are not all-or-nothing) falls back to the seed.
 * @param {{persona?:string, notes?:string}} payload - the turn body's carried buddy memory.
 * @param {{setting:string, user:string}} seed - the baked default (read once at boot).
 * @param {(t:string)=>{ok:boolean}} screen - the safety filter (`filter.js`).
 * @returns {{setting:string, user:string}}
 */
export function composeTurnMemory(payload, seed, screen) {
  const pick = (val, fallback) =>
    (typeof val === 'string' && val.trim() && screen(val).ok) ? val : fallback;
  return { setting: pick(payload && payload.persona, seed.setting), user: pick(payload && payload.notes, seed.user) };
}

/** Soft char budget for User.md; near it, the buddy proposes consolidation (not a hard error). */
export const USER_BUDGET = 1400;

/** Derive Champion.md from a sanitized manifest + project state (filename unchanged — it is the
 *  champion's profile per the P5 spec; only the generator is project-generic now). */
export function projectMarkdown(manifest, state) {
  const lines = ['# Champion Profile', `Project: ${manifest.title}${manifest.kidJob ? ` — ${manifest.kidJob}` : ''}`];
  const params = (manifest.params || []).filter((p) => state.params && p.name in state.params);
  if (params.length) lines.push('Settings:', ...params.map((p) => `- ${p.label}: ${state.params[p.name]}`));
  for (const s of manifest.slots || []) {
    const v = state.slots && state.slots[s.name];
    if (!v) continue;
    if (s.grouped) {
      const gs = Object.entries(v.groups || {}).map(([g, ids]) => `- ${g}: ${ids.length}`);
      lines.push(`${s.label}:`, ...(gs.length ? gs : ['- (none yet)']));
    } else {
      lines.push(`${s.label}: ${(v.items || []).length}`);
    }
  }
  const reads = (manifest.readouts || []).filter((r) => state.readouts && r.name in state.readouts);
  if (reads.length) lines.push('Readouts:', ...reads.map((r) => `- ${r.label}: ${state.readouts[r.name]}`));
  return lines.join('\n');
}
